### ISSUE TITLE
Date Time format is not working

### ISSUE THREAD

**Issue by sukhjinder-sdei** [jptangchina/jxcel#1]
I have the following date format in excel under column name DOB-: 
27-02-1980

I want to parse into my object
  @JxcelCell( value = "DOB",format = "dd-mm-yyyy")
    Date DOB;

this Date is  java.util.Date;

When I run code it throwgh following error

Exception in thread "main" java.lang.IllegalArgumentException: Invalid format: "36,892" is malformed at ",892"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
	at org.joda.time.DateTime.parse(DateTime.java:160)
	at org.joda.time.DateTime.parse(DateTime.java:149)
	at com.jptangchina.jxcel.JxcelParser.parseStringWithMatchedType(JxcelParser.java:81)
	at com.jptangchina.jxcel.JxcelParser.invokeDataSet(JxcelParser.java:65)
	at com.jptangchina.jxcel.JxcelParser.parseFromWorkbook(JxcelParser.java:43)
	at com.jptangchina.jxcel.JxcelParser.parseFromFile(JxcelParser.java:56)
	at ExcelUtil.main(ExcelUtil.java:12)

**Comment by jptangchina** [comment]
I really wish this did not get you too much trouble and thanks for your feedback.
I've fixed this in latest version 1.0.2 and I strongly suggest you use "dd-MM-yyyy" instead of "dd-mm-yyyy" to make sure you get the correct date value.
Thanks again.

**Comment by sukhjinder-sdei** [comment]
Thanks a lot
